require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '16.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
podfile_properties = JSON.parse(File.read(File.join(__dir__, '../node_modules/react-native/podfile.properties.json'))) rescue {}

install! 'cocoapods', :deterministic_uuids => false

target 'Unbound' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => config[:fabric_enabled],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true'
    )

    # FirebaseCoreInternal fix for Metadata.appintents conflict
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_SOURCE_FILE_NAMES'] ||= ''
        config.build_settings['EXCLUDED_SOURCE_FILE_NAMES'] += ' Metadata.appintents'
      end
    end

    # Fix for Xcode 14 resource bundle signing
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
        target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
          resource_bundle_target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          end
        end
      end
  end
end
